[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
update_changelog_on_bump = true
version = "0.1.1"
version_files = [
  "Cargo.toml:version =",
  "docs/conf.py:version = release",
  "pyproject.toml:version =",
  "python/logseq_doctor/__init__.py",
  "README.rst:github",
]
