# https://golangci-lint.run/usage/configuration/
linters:
  enable-all: true
  disable:
    # keep-sorted start
    - copyloopvar
    - depguard
    - forbidigo
    - gci
    - gochecknoinits
    - godox
    - gofmt
    - gofumpt
    - goimports
    - intrange
    - ireturn
    - paralleltest
    # keep-sorted end
