version: 2

project_name: logseq-doctor

before:
  hooks:
    - go mod download
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/lqd/main.go
    binary: lqd
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - docs/readme.md
      - LICENSE
      - docs/changelog.md
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  use: github-native
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

# https://goreleaser.com/customization/homebrew_casks/
homebrew_casks:
  - name: logseq-doctor
    commit_author:
      name: andreoliwa
      email: andreoliwa@sent.com
    commit_msg_template: "Cask update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Casks
    homepage: "https://github.com/andreoliwa/logseq-doctor"
    description: "Heal your Logseq Markdown files"
    license: "MIT"
    # Repository to push the generated files to.
    repository:
      pull_request:
        enabled: true
        draft: true
        base:
          branch: master
      owner: andreoliwa
      name: homebrew-formulae
      branch: release
      token: "{{ .Env.GITHUB_TOKEN }}"
