version: 2

project_name: logseq-doctor

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: ["tar.gz"]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: ["tar.gz"]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# https://goreleaser.com/customization/homebrew/
brews:
  - name: logseq-doctor
    commit_author:
      name: andreoliwa
      email: andreoliwa@sent.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    description: "Heal your Logseq Markdown files"
    license: "MIT"
    # Rename the executable to "lsdg"
    # https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#bininstall-foo
    install: |
      bin.install "logseq-doctor" => "lsdg"
    test: |
      assert_match "Logseq Doctor (Go) heals your Markdown files for Logseq.", shell_output("#{bin}/lsdg")
    # Repository to push the generated files to.
    repository:
      pull_request:
        enabled: true
      owner: andreoliwa
      name: homebrew-formulae
      branch: master
      token: "{{ .Env.GITHUB_TOKEN }}"
