# https://pre-commit.com/#creating-new-hooks
- id: tidy-up
  name: "logseq-doctor tidy-up"
  description: "Tidy up your Markdown files by removing empty bullets in any block"
  entry: lsd tidy-up
  language: python
  types:
    - markdown
